name: Create Release

on:
  # push:
  #   branches: [ main ]
  schedule:
    # Run midnight every monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Translate 
        if: vars.AUTO_UPDATE == 'true' && github.event_name != 'push'
        run: |
          curl -o jp.json -L https://github.com/po-po-po-pong/umaumacruise_customjson/raw/main/UmaMusumeLibrary.json
          curl -o files.json -L https://api.github.com/repos/noccu/umamusu-translate/contents/translations/mdb?ref=master
          jq --raw-output ".[] | select(.download_url != null).download_url" files.json > urls.txt
          mkdir mdb
          cd mdb
          curl --silent --remote-name-all $(cat ../urls.txt)
          cd ..
          node tools/autotl.js mdb jp.json libraries/UmaMusumeLibrary.json
          cp libraries/UmaMusumeLibrary.json libraries/UmaMusumeLibrary_v2.json

      - name: Zip JSON files
        run: zip -j UmaUmaCruise_EN-patch.zip libraries/*.json

      - uses: "softprops/action-gh-release@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: false
          name: "Latest update"
          files: UmaUmaCruise_EN-patch.zip
